<a href="https://colab.research.google.com/github/Narendrafulwaria/-Python-Projects/blob/main/Practice_Employee_Analysis_Dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data ={
      "Employee_id" : ["EMP001","EMP002","EMP003","EMP004","EMP005"],
      "Name" : ["Narendra","Rahul","Priya","Amit","Neha"],
      "Department" : ["IT","HR","Finance","IT","HR"],
      "Days_present" : [24,20,26,18,22],
      "Days_absent" : [2,6,0,8,4],
      "Performance_Score":[88,75,95,65,82]
      }

df = pd.DataFrame(data)
df

,Employee_id,Name,Department,Days_present,Days_absent,Performance_Score
0,EMP001,Narendra,IT,24,2,88
1,EMP002,Rahul,HR,20,6,75
2,EMP003,Priya,Finance,26,0,95
3,EMP004,Amit,IT,18,8,65
4,EMP005,Neha,HR,22,4,82

In [ ]:
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull())

  Employee_id      Name Department  Days_present  Days_absent  \
0      EMP001  Narendra         IT            24            2
1      EMP002     Rahul         HR            20            6
2      EMP003     Priya    Finance            26            0
3      EMP004      Amit         IT            18            8
4      EMP005      Neha         HR            22            4

   Performance_Score
0                 88
1                 75
2                 95
3                 65
4                 82
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_id        5 non-null      object
 1   Name               5 non-null      object
 2   Department         5 non-null      object
 3   Days_present       5 non-null      int64
 4   Days_absent        5 non-null      int64
 5   Performance_Score  5 non-null      int64
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes
None
       Days_present  Days_absent  Performance_Score
count      5.000000     5.000000           5.000000
mean      22.000000     4.000000          81.000000
std        3.162278     3.162278          11.597414
min       18.000000     0.000000          65.000000
25%       20.000000     2.000000          75.000000
50%       22.000000     4.000000          82.000000
75%       24.000000     6.000000          88.000000
max       26.000000     8.000000          95.000000
   Employee_id   Name  Department  Days_present  Days_absent  \
0        False  False       False         False        False
1        False  False       False         False        False
2        False  False       False         False        False
3        False  False       False         False        False
4        False  False       False         False        False

   Performance_Score
0              False
1              False
2              False
3              False
4              False

In [ ]:
#Attendance analysis

df["Attendance_pct"] = (df['Days_present']/(df['Days_present']+df['Days_absent'])*100).round(2)
df

,Employee_id,Name,Department,Days_present,Days_absent,Performance_Score,Attendance_pct
0,EMP001,Narendra,IT,24,2,88,92.31
1,EMP002,Rahul,HR,20,6,75,76.92
2,EMP003,Priya,Finance,26,0,95,100.00
3,EMP004,Amit,IT,18,8,65,69.23
4,EMP005,Neha,HR,22,4,82,84.62

In [ ]:
#performance analysis

def performance_analysis(performance_score):
    if performance_score >= 90:
      return 'Excellent'
    elif performance_score >= 80:
      return 'Good'
    elif performance_score >= 70:
      return 'Average'
    elif performance_score < 70:
      return 'Needs improvment'

df['Performance_Category'] = df['Performance_Score'].apply(performance_analysis)
df

,Employee_id,Name,Department,Days_present,Days_absent,Performance_Score,Attendance_pct,dept_avg,Performance_Category
0,EMP001,Narendra,IT,24,2,88,92.31,76.5,Good
1,EMP002,Rahul,HR,20,6,75,76.92,78.5,Average
2,EMP003,Priya,Finance,26,0,95,100.00,95.0,Excellent
3,EMP004,Amit,IT,18,8,65,69.23,76.5,Needs improvment
4,EMP005,Neha,HR,22,4,82,84.62,78.5,Good

In [ ]:
#department analysis

#1.Avg performance_score by department

def department_avg_score(department):
   avg_score = df[df['Department'] == department]['Performance_Score'].mean()
   return avg_score
print(department_avg_score('IT'))

#2.Avg attendance by department
def department_avg_attendance(department):
    avg_attendance =df[df['Department'] == department]['Attendance_pct'].mean().round(2)
    return avg_attendance
print(department_avg_attendance('IT'))

#3.Employee count
def employee_count(department):
    count = df[df['Department'] == department]['Employee_id'].count()
    return count
print(employee_count('IT'))

76.5
80.77
2

In [ ]:
#1. top 3 employees by performance_score
df.sort_values(by='Performance_Score',ascending=False).head(3)

#2. employees with attendance less 80%
print(df[df['Attendance_pct'] < 80])

df.groupby('Department')['Attendance_pct'].mean().round(2)
# df.loc[(df['Attendance_pct']<80),['Name','Attendance_pct']]

# employees with performance above department performance avg
df['dept_avg'] = df.groupby("Department")["Performance_Score"].transform('mean').round(2)

df

# students above average

df[df['Performance_Score'] > df['dept_avg']]

  Employee_id   Name Department  Days_present  Days_absent  Performance_Score  \
1      EMP002  Rahul         HR            20            6                 75
3      EMP004   Amit         IT            18            8                 65

   Attendance_pct
1           76.92
3           69.23

,Employee_id,Name,Department,Days_present,Days_absent,Performance_Score,Attendance_pct,dept_avg
0,EMP001,Narendra,IT,24,2,88,92.31,76.5
4,EMP005,Neha,HR,22,4,82,84.62,78.5

In [ ]:
performance_score = np.array(df['Performance_Score'])

performance_score.mean()
performance_score.max()
performance_score.min()
performance_score.std()

np.float64(10.373041983911952)

In [ ]:
# dashboard
print("--DashBoard--")
count = df['Employee_id'].count()
print(f"Total employees: {count}")
Highest_performance = df['Performance_Score'].max()
print(f"Highest performance: {Highest_performance}")
Lowest_performance = df['Performance_Score'].min()
print(f"Lowest performance: {Lowest_performance}")
avg_attendance = df['Attendance_pct'].mean().round(2)
print(f"Average attendance: {avg_attendance}")
best_department = df.groupby('Department')['Performance_Score'].mean().idxmax()
print(f"Best department: {best_department}")
Need_imp_count = df[df['Performance_Category']=='Needs improvment']['Name'].count()
print(f"Number of employees need improvement: {Need_imp_count}")

--DashBoard--
Total employees: 5
Highest performance: 95
Lowest performance: 65
Average attendance: 84.62
Best department: Finance
Number of employees need improvement: 1